<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite1" duration-ms="27023" started-at="2017-09-20T11:01:36Z" finished-at="2017-09-20T11:02:03Z">
    <groups>
    </groups>
    <test name="Nopackage" duration-ms="27023" started-at="2017-09-20T11:01:36Z" finished-at="2017-09-20T11:02:03Z">
      <class name="Main">
        <test-method status="PASS" signature="SetUp()[pri:0, instance:Main@60215eee]" name="SetUp" is-config="true" duration-ms="6421" started-at="2017-09-20T14:01:36Z" finished-at="2017-09-20T14:01:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method status="FAIL" signature="correctLogin()[pri:0, instance:Main@60215eee]" name="correctLogin" duration-ms="20480" started-at="2017-09-20T14:01:42Z" finished-at="2017-09-20T14:02:02Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://live.easyerp.com/#login] but found [https://live.easyerp.com/#easyErp/reportsDashboard]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://live.easyerp.com/#login] but found [https://live.easyerp.com/#easyErp/reportsDashboard]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at Main.correctLogin(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.TestNG.privateMain(TestNG.java:1338)
	at org.testng.TestNG.main(TestNG.java:1307)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- correctLogin -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:Main@60215eee]" name="tearDown" is-config="true" duration-ms="115" started-at="2017-09-20T14:02:02Z" finished-at="2017-09-20T14:02:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Main -->
    </test> <!-- Nopackage -->
  </suite> <!-- Suite1 -->
</testng-results>
